### ISSUE TITLE
TODO for v0.1.0

### ISSUE THREAD

**Issue by nabeken** [nabeken/terraform-aws-ecs-drain-lambda#1]
## TODO

- [x] EventBridge support
- [x] Waiting for https://github.com/getsocial-rnd/ecs-drain-lambda/pull/12 to be merged
  - [x] If they don't make it, I'll build a binary and upload it to this repository as a workaround
- [x] Bump the version
- [x] Release v0.1.0

**Comment by nabeken** [comment]
https://registry.terraform.io/modules/nabeken/ecs-drain-lambda/aws/latest
